"use client";

import { motion } from "framer-motion";
import { ArrowLeft, Cloud, Github, Layers, Cpu, Lightbulb, TrendingUp, AlertCircle } from "lucide-react";
import Link from "next/link";

const techChoices = [
  {
    choice: "AWS AppSync over custom REST API",
    reason:
      "AppSync provides built-in GraphQL subscriptions for real-time updates, managed resolvers, and direct DynamoDB integration — eliminating the need to build and maintain a WebSocket server.",
  },
  {
    choice: "DynamoDB single-table design",
    reason:
      "Social data (posts, comments, likes, events) has high read throughput and variable access patterns. Single-table DynamoDB with composite keys handles this efficiently at scale.",
  },
  {
    choice: "AWS Cognito for auth",
    reason:
      "Managed user pools with JWT tokens, MFA support, and built-in AppSync integration. No need to build and maintain a custom auth system.",
  },
  {
    choice: "AWS Amplify for hosting and CI/CD",
    reason:
      "Amplify connects directly to GitHub and auto-deploys on push. Built-in CDN, SSL, and environment management — zero infrastructure to manage for the frontend.",
  },
  {
    choice: "Lambda for business logic",
    reason:
      "Serverless functions scale automatically with usage. Event-driven architecture means no idle compute costs and no servers to patch or maintain.",
  },
];

const challenges = [
  {
    challenge: "Real-time subscription performance at scale",
    solution:
      "Designed DynamoDB access patterns to minimize hot partitions. Used AppSync subscription filters to ensure users only receive relevant updates, reducing unnecessary data transfer.",
  },
  {
    challenge: "IAM permission complexity",
    solution:
      "Adopted least-privilege IAM policies from the start. Used Cognito identity pools to map authenticated users to specific IAM roles with scoped DynamoDB and S3 permissions.",
  },
  {
    challenge: "GraphQL schema design for social features",
    solution:
      "Iterated on the schema to balance flexibility and performance. Used connection patterns for paginated feeds and denormalized data where read performance was critical.",
  },
  {
    challenge: "Media upload handling",
    solution:
      "Used S3 pre-signed URLs generated by Lambda — the client uploads directly to S3 without routing through the API, keeping the backend lean and uploads fast.",
  },
];

const futureImprovements = [
  "Push notifications via SNS/SES",
  "Advanced event discovery with location filtering",
  "Direct messaging between users",
  "Analytics dashboard for campus admins",
  "Mobile app with React Native",
  "DynamoDB Streams for event-driven workflows",
];

export default function CaseStudyConnectNest() {
  return (
    <div className="min-h-screen bg-[#050810] pt-24 pb-20">
      <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8">

        {/* Back link */}
        <motion.div
          initial={{ opacity: 0, x: -10 }}
          animate={{ opacity: 1, x: 0 }}
          transition={{ duration: 0.4 }}
          className="mb-10"
        >
          <Link
            href="/#projects"
            className="inline-flex items-center gap-2 text-sm text-slate-500 hover:text-white transition-colors"
          >
            <ArrowLeft className="w-4 h-4" aria-hidden="true" />
            Back to Projects
          </Link>
        </motion.div>

        {/* Header */}
        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.6 }}
          className="mb-12"
        >
          <div className="flex items-center gap-3 mb-4">
            <div className="w-12 h-12 rounded-xl bg-cyan-500/10 flex items-center justify-center" aria-hidden="true">
              <Cloud className="w-6 h-6 text-cyan-400" />
            </div>
            <div>
              <span className="text-xs font-mono text-cyan-400 uppercase tracking-widest">Case Study</span>
              <h1 className="text-3xl md:text-4xl font-black text-white">ConnectNest</h1>
            </div>
          </div>
          <p className="text-lg text-slate-400 leading-relaxed max-w-2xl">
            A cloud-native campus engagement platform built entirely on the AWS Amplify ecosystem — real-time social features, serverless architecture, and production-ready auth.
          </p>
          <div className="flex flex-wrap gap-3 mt-6">
            <a
              href="https://github.com/kirtan0515"
              target="_blank"
              rel="noopener noreferrer"
              className="inline-flex items-center gap-2 px-4 py-2 rounded-lg glass border border-white/10 hover:border-cyan-500/30 text-sm text-slate-300 hover:text-white transition-all"
            >
              <Github className="w-4 h-4" aria-hidden="true" />
              View on GitHub
            </a>
          </div>
        </motion.div>

        <div className="space-y-12">

          {/* Overview */}
          <Section title="Overview" icon={Layers} color="cyan">
            <p className="text-slate-400 leading-relaxed mb-4">
              Campus communities lack a centralized, real-time platform for students to connect, share events, and engage. Most solutions are either too generic or not built with cloud-native architecture in mind.
            </p>
            <p className="text-slate-400 leading-relaxed">
              ConnectNest is a full-stack social platform built entirely on AWS managed services — demonstrating how to architect a real-time, scalable application without managing servers.
            </p>
          </Section>

          {/* What it does */}
          <Section title="What It Does" icon={Cloud} color="cyan">
            <ul className="space-y-3">
              {[
                "Real-time social feed with posts, comments, and likes via GraphQL subscriptions",
                "Event creation and discovery with campus-focused filtering",
                "Group management with role-based membership",
                "User profiles with avatar uploads to S3",
                "Cognito authentication with role-based access control",
                "CI/CD pipeline via GitHub Actions for automated AWS deployment",
                "CloudWatch monitoring and IAM access controls for observability",
              ].map((item) => (
                <li key={item} className="flex items-start gap-3 text-sm text-slate-400">
                  <span className="w-1.5 h-1.5 rounded-full bg-cyan-400 mt-1.5 shrink-0" aria-hidden="true" />
                  {item}
                </li>
              ))}
            </ul>
          </Section>

          {/* Architecture */}
          <Section title="Architecture" icon={Cpu} color="cyan">
            <div className="glass-light rounded-xl p-5 font-mono text-sm text-slate-300 leading-loose mb-6">
              <p className="text-cyan-400 mb-2">Request flow:</p>
              <p>React SPA (Amplify hosting + CDN)</p>
              <p className="pl-4 text-slate-500">→ AWS AppSync (GraphQL API + subscriptions)</p>
              <p className="pl-8 text-slate-500">→ Lambda resolvers (business logic)</p>
              <p className="pl-8 text-slate-500">→ DynamoDB (single-table social data)</p>
              <p className="pl-8 text-slate-500">→ S3 (media, avatars via pre-signed URLs)</p>
              <p className="pl-4 text-slate-500">→ Cognito (auth + JWT + role-based access)</p>
              <p className="mt-3 text-cyan-400">Infrastructure:</p>
              <p>AWS Amplify (hosting + CI/CD) · CloudWatch (monitoring)</p>
              <p>IAM least-privilege policies · GitHub Actions (deployment)</p>
            </div>
          </Section>

          {/* Tech choices */}
          <Section title="Tech Choices & Why" icon={Lightbulb} color="cyan">
            <div className="space-y-4">
              {techChoices.map((item) => (
                <div key={item.choice} className="glass rounded-xl p-5 border border-cyan-500/10">
                  <p className="text-sm font-semibold text-white mb-1">{item.choice}</p>
                  <p className="text-xs text-slate-400 leading-relaxed">{item.reason}</p>
                </div>
              ))}
            </div>
          </Section>

          {/* Challenges */}
          <Section title="Challenges & Solutions" icon={AlertCircle} color="cyan">
            <div className="space-y-4">
              {challenges.map((item) => (
                <div key={item.challenge} className="glass rounded-xl p-5 border border-white/5">
                  <p className="text-xs font-mono text-cyan-400 uppercase tracking-wider mb-1">Challenge</p>
                  <p className="text-sm font-semibold text-white mb-2">{item.challenge}</p>
                  <p className="text-xs font-mono text-emerald-400 uppercase tracking-wider mb-1">Solution</p>
                  <p className="text-xs text-slate-400 leading-relaxed">{item.solution}</p>
                </div>
              ))}
            </div>
          </Section>

          {/* What I learned */}
          <Section title="What I Learned" icon={TrendingUp} color="cyan">
            <ul className="space-y-3">
              {[
                "DynamoDB single-table design requires upfront access pattern planning — but pays off in performance",
                "AppSync subscriptions are powerful but require careful filter design to avoid over-broadcasting",
                "IAM least-privilege is easier to maintain when you design it from the start, not retrofit it later",
                "Amplify CI/CD dramatically reduces deployment friction — push to main, it deploys",
                "Pre-signed S3 URLs are the right pattern for client-side media uploads — keeps the API lean",
              ].map((item) => (
                <li key={item} className="flex items-start gap-3 text-sm text-slate-400">
                  <span className="w-1.5 h-1.5 rounded-full bg-emerald-400 mt-1.5 shrink-0" aria-hidden="true" />
                  {item}
                </li>
              ))}
            </ul>
          </Section>

          {/* Roadmap */}
          <Section title="Roadmap" icon={TrendingUp} color="cyan">
            <div className="flex flex-wrap gap-2">
              {futureImprovements.map((item) => (
                <span
                  key={item}
                  className="px-3 py-1.5 rounded-lg text-xs font-medium bg-cyan-500/10 text-cyan-300 border border-cyan-500/20"
                >
                  {item}
                </span>
              ))}
            </div>
          </Section>

        </div>
      </div>
    </div>
  );
}

function Section({
  title,
  icon: Icon,
  color,
  children,
}: {
  title: string;
  icon: React.ElementType;
  color: string;
  children: React.ReactNode;
}) {
  const colorClass = color === "cyan" ? "text-cyan-400" : "text-violet-400";
  const bgClass = color === "cyan" ? "bg-cyan-500/10" : "bg-violet-500/10";

  return (
    <motion.div
      initial={{ opacity: 0, y: 20 }}
      whileInView={{ opacity: 1, y: 0 }}
      viewport={{ once: true, margin: "-40px" }}
      transition={{ duration: 0.5 }}
    >
      <div className="flex items-center gap-3 mb-5">
        <div className={`w-8 h-8 rounded-lg ${bgClass} flex items-center justify-center`} aria-hidden="true">
          <Icon className={`w-4 h-4 ${colorClass}`} />
        </div>
        <h2 className="text-lg font-bold text-white">{title}</h2>
      </div>
      {children}
    </motion.div>
  );
}
